### ISSUE TITLE
Cannot receive/send any message when acl is configured

### ISSUE THREAD

**Issue by abbychau** [wind-c/comqtt#92]
I set this config:
![image](https://github.com/wind-c/comqtt/assets/350283/4432c001-d78f-4d66-a6a7-db53fd05ad15)

and the client receives no messages after that.

if acl-mode is 0, then the results can be received
![image](https://github.com/wind-c/comqtt/assets/350283/8ad0919f-074d-4021-ba46-ffd92df4ab83)

my acl config block is :
```
acl:
  table: acl
  user-column: username # or client_id, set this parameter based on the actual field name
  topic-column: topic
  access-column: access  # 0 Deny、1 publish (Write)、2 subscribe (Read)、3 pubsub (ReadWrite)
 ```
